### ISSUE TITLE
Note to reviewer

### ISSUE THREAD

**Issue by Naledi-Dikgale** [stephenkati/gaming_console_reservation_back_end#15]
### There are 4 people in this team:

@stephenkati, @Yacoubou-seidou, @Timbar09, @Naledi-Dikgale.

[The link to the Kanban board ](https://github.com/stephenkati/gaming_console_reservation_back_end/projects/1)

In this project, we are going to build the Final Capstone Project based on an app for reserving consoles.
 

- [ ] Kanban board screenshot below.

![Kanban](https://github.com/stephenkati/gaming_console_reservation_back_end/assets/117156742/995091b5-d606-49c6-b6c9-2f5ef4237c5e)

**Comment by Meltrust** [comment]
Hi @Naledi-Dikgale,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a kanban board screenshot.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @Naledi-Dikgale,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned,  pointed and have descriptions✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
